//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Axis.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RobotMehes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RobotMehes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Axis.Resources.RobotMehes", typeof(RobotMehes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IRB120mesh {
            get {
                object obj = ResourceManager.GetObject("IRB120mesh", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IRB140_6kg_081mmesh {
            get {
                object obj = ResourceManager.GetObject("IRB140_6kg_081mmesh", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IRB1520ID_4kg_150mmesh {
            get {
                object obj = ResourceManager.GetObject("IRB1520ID_4kg_150mmesh", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IRB1600_6kg_120mmesh {
            get {
                object obj = ResourceManager.GetObject("IRB1600_6kg_120mmesh", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IRB1660ID_4kg_155mmesh {
            get {
                object obj = ResourceManager.GetObject("IRB1660ID_4kg_155mmesh", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IRB2600_12kg_185mmesh {
            get {
                object obj = ResourceManager.GetObject("IRB2600_12kg_185mmesh", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IRB2600_12kg_20kg_165mmesh {
            get {
                object obj = ResourceManager.GetObject("IRB2600_12kg_20kg_165mmesh", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IRB2600ID_15kg_185mmesh {
            get {
                object obj = ResourceManager.GetObject("IRB2600ID_15kg_185mmesh", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IRB2600ID_8kg_200mmesh {
            get {
                object obj = ResourceManager.GetObject("IRB2600ID_8kg_200mmesh", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IRB4600_20kg_250mmesh {
            get {
                object obj = ResourceManager.GetObject("IRB4600_20kg_250mmesh", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IRB4600_40kg_255mmesh {
            get {
                object obj = ResourceManager.GetObject("IRB4600_40kg_255mmesh", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IRB4600_45kg_60kg_205mmesh {
            get {
                object obj = ResourceManager.GetObject("IRB4600_45kg_60kg_205mmesh", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IRB6620mesh {
            get {
                object obj = ResourceManager.GetObject("IRB6620mesh", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IRB6650S_100kg_350mmesh {
            get {
                object obj = ResourceManager.GetObject("IRB6650S_100kg_350mmesh", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IRB6650S_125kg_350mmesh {
            get {
                object obj = ResourceManager.GetObject("IRB6650S_125kg_350mmesh", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IRB6650S_190kg_300mmesh {
            get {
                object obj = ResourceManager.GetObject("IRB6650S_190kg_300mmesh", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IRB6650S_200kg_300mmesh {
            get {
                object obj = ResourceManager.GetObject("IRB6650S_200kg_300mmesh", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IRB6650S_90kg_390mmesh {
            get {
                object obj = ResourceManager.GetObject("IRB6650S_90kg_390mmesh", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IRB6700_150kg_320mmesh {
            get {
                object obj = ResourceManager.GetObject("IRB6700_150kg_320mmesh", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IRB6700_155kg_285mmesh {
            get {
                object obj = ResourceManager.GetObject("IRB6700_155kg_285mmesh", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IRB6700_175kg_305mmesh {
            get {
                object obj = ResourceManager.GetObject("IRB6700_175kg_305mmesh", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IRB6700_200kg_260mmesh {
            get {
                object obj = ResourceManager.GetObject("IRB6700_200kg_260mmesh", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IRB6700_205kg_280mmesh {
            get {
                object obj = ResourceManager.GetObject("IRB6700_205kg_280mmesh", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IRB6790_205kg_280mmesh {
            get {
                object obj = ResourceManager.GetObject("IRB6790_205kg_280mmesh", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IRB6790_235kg_265mmesh {
            get {
                object obj = ResourceManager.GetObject("IRB6790_235kg_265mmesh", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
