name: Build and Test

on:
  pull_request:
  push:
    branches: 
    - main
    - master
    - development
    paths-ignore:
    - '**.md'
    - '**.yml'

jobs:
  build-package:
    name: Build the Grasshopper package
    runs-on: windows-latest
    env:
      AUTHID:  ${{ secrets.AUTHID }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Install dependencies
      run: dotnet restore .\Axis.sln -v d
    - name: Build
      run: dotnet build --configuration Yak --no-restore -v d
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      
    # Get the assembly version
    - uses: dotnet/nbgv@master
      with:
        path: .\Plugin
        setAllVars: true 
